---
title: "Papers"
---

<br>
<font size="5">[Google Scholar Page](https://scholar.google.com/citations?user=1jdvTZwAAAAJ&hl=en)</font> 
<br>

COPYRIGHT NOTICE: The material listed here are copyrighted. Personal use of this material is permitted. However, permission to reprint/publish this material for advertising or promotional purposes or for creating new collective works for resale or redistribution to servers or lists, or to reuse any copyrighted component of this work in other works must be obtained from the copyright holder.

## 2025
K. Goode, **J. D. Tucker**, D. Ries, and H. Hoffman, "An Explainable Pipeline for Machine Learning with Functional Data", *Journal of Data Science*, in revision, 2025. [arxiv preprint](https://arxiv.org/abs/2501.07602)

N. Winovich, L. Moynihan, O. Abdelrahman, R. West, S. Dauphin, **J. D. Tucker**, G. Huerta, K. Potter, R. Forrest, C. Phillips, and M. Ebeida, "VoroClust: Scalable Clustering for Remote Sensing", *IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing*, submitted, 2024.

J. Adams, B. Berman, J. Michalenko, **J. D. Tucker**, "Conformal Anomaly Detection for Functional Data with Elastic Distance Metrics", *arXiv:2504.01172*, 2025. [arxiv preprint](https://arxiv.org/abs/2504.01172)

J. E. Borgert, J. Hannig, **J. D. Tucker**, L. Arbeeva, A. N. Buck, Y. M. Golightly, S. P. Messier, A. E. Nelson, and J. S. Marron, "Elastic Shape Analysis of Movement Data", *JASA Case Studies and Applications*, 10.1080/01621459.2025.2572778, 2025. [PDF](Papers/JASA25_Borgert.pdf)

## 2024
A. Heiskala, **J. D. Tucker**, P. Choudhary, R. Nedelec, J. Ronkainen, O. Sarala, M. Järvelin, M. J. Sillanpääm, and S. Sebert, "Timing based clustering of childhood BMI trajectories reveal differential maturational patterns; Study in the Northern Finland Birth Cohorts 1966 and 1986", *International Journal of Obesity*, 10.1038/s41366-025-01714-8, 2024. [PDF](Papers/Heiskala_et_al-2025-International_Journal_of_Obesity.pdf)

A. McCombs, M. A. Ausdemore, K. Goode, J. G. Huerta, K. Shuler, **J. D. Tucker**, A. Zhang, and D. Ries, “Inverse prediction of PuO2 processing conditions using Bayesian seemingly unrelated regression with functional data”, *Frontiers in Nuclear Engineering-Nuclear Materials*. 10.3389/fnuen.2024.1331349, 2024. [PDF](Papers/SUR24FNE.pdf)

D. Francom, **J. D. Tucker**, J. G. Huerta, K. Shuler, and D. Ries, "Elastic Bayesian Model Calibration", *SIAM/ASA Journal on Uncertainty Quantification*, vol. 13, no. 1, 2025. [PDF](Papers/Francom-2025-Calibration-JUQ.pdf)

## 2023
R. Darling, G. S. Clark, and **J. D. Tucker**, "Hidden Ancestor Graphs: Models for Detagging Property Graphs", *arXiv:2102.09581 [math.PR]*. 2023 [arxiv preprint](https://arxiv.org/abs/2102.09581)

J. Brown, J. P. Davis, **J. D. Tucker**, J. G. Huerta, and K. Shuler, "Quantifying uncertainty in analysis of shockless dynamic compression experiments on platinum, Part 2: Bayesian model calibration", *Journal of Applied Physics*, vol. 134, no. 23, 2023. [PDF](Papers/JAP23_calibration.pdf)

Christian A. Pattyn, Alexander W. Edstrom, Andres L. Sanchez, Karl Westlake, John D. van der Laan, **J. Derek Tucker**, Jessica Jones, Kaylin Hagopian, Joshua C. Shank, Lilian K. Casias, Jeremy B. Wright, "Event-based sensing for the detection of modulated signals in degraded visual environments", *Proc. SPIE 12514, Image Sensing Technologies: Materials, Devices, Systems, and Applications X, 1251409*, 2023. [PDF](Papers/SPIE23.pdf)

**J. D. Tucker** and D. Yarger, "Elastic Functional Changepoint Detection of Climate Impacts from Localized Sources", *Envirometrics*, 10.1002/env.2826, 2023. [PDF](Papers/Envirometics23_ElasticChangeDetection.pdf) **2024 Wiley-TIES Best Environmetrics Paper Award**

K. Rumsey, and J. G. Huerta, and **J. D. Tucker**, "A Localized Ensemble of Approximate Gaussian Processes for Fast Sequential Emulation", *Stat*, 10.1002/sta4.576, 2023. [PDF](Papers/leapGP23.pdf)

**J. D. Tucker**, M. T. Martinez, and J. M. Laborde, "Dimensionality Reduction using Elastic Measures", *Stat*, 10.1002/sta4.551, 2023. [PDF](Papers/Stat23.pdf)

J. Upston, D. Sulsky, **J. D. Tucker**, and Y. Guan, "CIEL\*Ch color map for visualization and analysis of sea ice motion", *Journal of Computational and Applied Mathematics*, 10.1016/j.cam.2023.115126, 2023. [PDF](Papers/1-s2.0-S0377042723000705-main.pdf)

## 2022
M. A. Ausdemore, A. McCombs, D. Ries, A. Zhang, K. Shuler, K. Goode, **J. D. Tucker** and J. G. Huerta, “A Probabilistic Inverse Prediction Method for Predicting Plutonium Processing Conditions”, *Frontiers in Nuclear Engineering-Nuclear Materials*. 10.3389/fnuen.2022.1083164, 2022.[PDF](Papers/PuBASS_Frontiers_2022.pdf)

D. Ries, A. Zhang, **J. D. Tucker**, K. Shuler, and  M. Ausdemore, "A framework for inverse prediction using functional response data", *JCISE*, 10.1115/1.4053752, 2022 [PDF](Papers/JCISE-21-1393.pdf)

## 2021
L. Patel, L. Shand, **J. D. Tucker**, and  G. Huerta, "Spatio-temporal extreme event modeling of terror insurgencies", *arXiv:2110.08363 [stat.AP]*, 2021 [arxiv](https://arxiv.org/abs/2110.08363)

T. Harris, B. Li, and **J. D. Tucker**. "Scalable Multiple Changepoint Detection for Functional Data Sequences", *Environmetrics*, 10.1002/env.2710, 2021. [PDF](Papers/Harris_Environmetrics_21.pdf) 

C. Ting, N. Johson, U. Onunkwo, and **J. D. Tucker**. "Faster classification using compression analytics", *IEEE ICDM Workshop on Data Mining and Machine Learning for Cybersecurity*, 2021. [PDF](Papers/IEEEDML_CYber21.pdf)

**J. D. Tucker**, L. Shand, and K. Chowdhary. "Multimodal Bayesian Registration of Noisy Functions using Hamiltonian Monte Carlo", *Computational Statistics and Data Analysis*, 10.1016/j.csda.2021.107298, 2021. [PDF](Papers/CSDA_Bayesian_21.pdf)

## 2020
X. Zhang, S. Kurtek, O. Chkrebtii, and **J. D. Tucker**, "Elastic $k$-means clustering of functional data for posterior exploration, with an application to inference on acute respiratory infection dynamics", *arXiv:2011.12397 [stat.ME]*, 2020 [arxiv](http://arxiv.org/abs/2011.12397)

A. H. Foss, R. B. Lehoucq, W. Z. Stuart, **J. D. Tucker**, and J. W. Berry, "A Deterministic Hitting-Time Moment Approach to Seed-set Expansion over a Graph", *arXiv:2011.09544 [cs.SI]*, 2020. [arxiv](http://arxiv.org/abs/2011.09544)

L. Patel, L. Shand, **J. D. Tucker**, and G. Huerta, "Assessing Extreme Value Analysis to predict rare events from the Global Terrorism Database,'' *Proc JSM*, August 2020 [PDF](Papers/JSM20.pdf)

T. Harris, B. Li, N. J. Steiger, J. E. Smerdon, N. Narisetty, and **J. D. Tucker**. "Testing the exchangeability of two ensembles of spatial processes - Evaluating proxy influence in assimilated paleoclimate reconstructions"  *Journal of the American Statistical Association*, 10.1080/01621459.2020.1799810, 2020. [[PDF](Papers/JASA20_proxy.pdf)
| [R](Code/JASA20_proxy_supp.zip)]

C. King, N. Martin, and **J. D. Tucker**. "Bounding Uncertainty in Functional Data: A Case Study in Reliability" *Quality Engineering*, vol. 33, no. 1, 2021. [PDF](Papers/King_QE_20.pdf)

T. Harris, **J. D. Tucker**, B. Li, and L. Shand, "Elastic depths for detecting shape anomalies in functional data," *Technometrics*, 10.1080/00401706.2020.1811156, 2020. [[PDF](Papers/Technometrics20_edepth.pdf)
| [R](Code/Technometrics20_edepth_supp.zip)]

M. K. Ahn, **J. D. Tucker**, W. Wu, and A. Srivastava. "Regression Models Using Shapes of Functions as Predictors" *Computational Statistics and Data Analysis*, 10.1016/j.csda.2020.107017, 2020. [PDF](Papers/Ahn_CSDA_20.pdf)

S. Reza, N. Martin, T. Buchheit, and **J. D. Tucker**, "Tolerance Bound Calculation for Compact Model Calibration Using Functional Data Analysis," Proc ETDM20, 2020.

## 2019
**J. D. Tucker**, J. R. Lewis, C. King, and S. Kurtek, "A Geometric Approach for Computing Tolerance Bounds for Elastic Functional Data," *Journal of Applied Statistics*, vol. 47, no 3. pp. 481-505, 2019. [PDF](Papers/JAS20_TB.pdf)

Y. Guan, C. Sampson, **J. D. Tucker**, W. Chang, A. Mondal, M. Haran, and D. Sulsky, "Computer model calibration based on image warping metrics: an application for sea ice deformation," *Journal of Agricultural, Biological and Environmental Statistics*, vol 41, pp 444–463, 2019 [PDF](Papers/Guan2019_Article_ComputerModelCalibrationBasedO.pdf)

## 2018
**J. D. Tucker**, L. Shand, and J. R. Lewis, "Handling Missing Data in Self-Exciting Point Process Models," *Spatial Statistics*, vol. 29. pp. 160-176, 2019. [PDF](Papers/SPATSTAT18_STPP.pdf)

**J. D. Tucker**, J. R. Lewis, and A. Srivastava, "Elastic Functional Principal Component Regression," *Statistical Analysis and Data Mining*, vol. 12, no. 2, pp. 101-115, 2019. [PDF](Papers/SADM18_elastic_regression.pdf)

T. Harris, B. Li, N. Steiger, J. Smerdon, and **J. D. Tucker**. "Evaluating Proxy Influence in Data Assimilation," *Proc Climate Informatics*, September 2018

T. Harris, B. Li, N. Steiger, J. Smerdon, and **J. D. Tucker**. "Evaluating proxy influence in data assimilation based climate field reconstruction,." *Proc JSM*, August 2018

M. K. Ahn, **J. D. Tucker**, W. Wu, and A. Srivastava. "Elastic handling of predictor phase in functional regression models." *International Workshop on DIFF-CVML: Differential Geometry in Computer Vision and Machine Learning, IEEE Conference on Computer Vision and Pattern Recognition (CVPR) Workshop*, June 2018. [PDF](Papers/CVPR18.pdf)

## 2017
J. Ramirez, M. Orini, **J. D. Tucker**, P. Laguna, and E. Pueyo, "Variability of Ventricular Repolarization Dispersion Quantified by Time-Warping the Morphology of the T-waves," *IEEE Transactions on Biomedical Engineering*, vol. 64, no. 7, pp. 1619-1630, 2017. [PDF](Papers/TBME_Ramirez.pdf)

## 2016
D. Bryner, F. Huffer, M. M. Rosenthal, **J. D. Tucker**, and A. Srivastava, "Linear Minelayer Trajectory Estimation Using Cluttered Point Cloud Data," *Computational Statistics and Data Analysis*, vol. 102, pp. 1-22, October 2016 [PDF](Papers/darshan_csda_2016.pdf)

J. Ramirez, M. Orini, **J. D. Tucker**, P. Laguna, and E. Pueyo, "An Index for T‐wave Pointwise Amplitude Variability Quantification,'' *Proc CinC (Mortara Winner)*, September 2016. [PDF](Papers/CINC16.pdf)

**J. D. Tucker**, "Functional Statistical Process Control using Elastic Methods,'' *Proc JSM*, August 2016. [PDF](Papers/JSM16.pdf)

D. Bryner, F. Huffer, A. Srivastava, and **J. D. Tucker**, "Underwater Mine Detection In Clutter Data Using Spatial Point Process Models," *IEEE Journal of Oceanic Engineering*, vol 41, no. 3. pp 670-681, 2016 [PDF](Papers/JOE-07398189.pdf)

T. G-Michael, B. Marchand, **J. D. Tucker**, D. D. Sternlicht, T. M. Marston, and M. R. Azimi-Sadjadi, "Image-based Automated Change Detection for Synthetic Aperture Sonar," *IEEE Journal of Oceanic Engineering*, vol 41, no. 3. pp 592-612, 2016. [PDF](Papers/JOE-07323881.pdf)

T. G-Michael, **J. D. Tucker**, and R. R. Roberts, "Statistically Normalized Coherent Change Detection for Synthetic Aperture Sonar Imagery," *Proc SPIE*, April 2016. [PDF](Papers/SPIE16.pdf)

## 2014
**J. D. Tucker**, W. Wu, and A. Srivastava, "Phase-Amplitude Separation of Proteomics Data Using Extended Fisher-Rao Metric," *Electronic Journal of Statistics*, vol 8, no. 2. pp 1724-1733, 2014. [[PDF](Papers/euclid.ejs.1414588155.pdf) | [Code](https://cran.r-project.org/web/packages/fdasrvf/index.html)]

T. G-Michael, B. Marchand, **J. D. Tucker**, D. D. Sternlicht, and T. M. Marston,"Automated Change Detection for Synthetic Aperture Sonar," *Proc SPIE*, May 2014. [PDF](Papers/spie14.pdf)

**J. D. Tucker**, W. Wu, and A. Srivastava, "Analysis of signals under compositional noise with applications to SONAR data," *IEEE Journal of Oceanic Engineering*, vol 29, no. 2. pp 318-330, Apr 2014. [[PDF](Papers/IEEEJOE_AC.pdf) | [Code](https://cran.r-project.org/web/packages/fdasrvf/index.html)]

## 2013
**J. D. Tucker**, W. Wu, and A. Srivastava, "Generative Models for Function Data using Phase and Amplitude Separation," *Computational Statistics and Data Analysis*, vol. 61, pp. 50-66, May 2013. [[PDF](Papers/CSDA_PCA_12.pdf)
| [R](https://cran.r-project.org/web/packages/fdasrvf/index.html)
| [MATLAB](https://github.com/jdtuck/fdasrvf_MATLAB)
| [Python](https://github.com/jdtuck/fdasrsf_python)
| [Julia](https://github.com/jdtuck/ElasticFDA.jl)]

## 2012
**J. D. Tucker**, W. Wu, and A. Srivastava, "Analysis of Signals Under Compositional Noise with Application to SONAR Data," *Proc. of MTS/IEEE Oceans 2012 Conference*, pp. 1-6, Oct. 2012. [PDF](Papers/Oceans12.pdf)

## 2011
**J. D. Tucker** and N. Klausner, "Compressive Sensing for Gauss-Gauss Detection,'' *Proc. of IEEE SMC 2011 Conference*, pp. 3335-3340, Oct. 2011. [PDF](Papers/SMC11.pdf)

J. C. Isaacs and **J. D. Tucker**, "Diffusion features for target specific recognition with synthetic aperture sonar raw signals and acoustic color," *Computer Vision and Pattern Recognition Workshops (CVPRW), 2011 IEEE Computer Society Conference on*, pp.27-32, 20-25 June 2011. [PDF](Papers/CVPR11.pdf)

**J. D. Tucker** and A. Srivastava,"Statistical analysis and classification of acoustic color functions,'' *Proc SPIE*, vol. 8017, pp. O1-O10, April 2011. [PDF](Papers/SPIE11.pdf)

**J. D. Tucker** and M. R. Azimi-Sadjadi, "Coherence-based underwater target detection from multiple sonar platforms," *IEEE Journal of Oceanic Engineering*, vol. 36, no. 1, pp. 37-51, Jan. 2011. [PDF](Papers/JOE11.pdf)

J. C. Isaacs and **J. D. Tucker**, "Signal diffusion features for automatic target recognition in synthetic aperture sonar," *Proc of IEEE DSP/SPE 2011 Workshop*, pp.461-465, Jan. 2011. [PDF](Papers/DSPE11-2.pdf)

**J. D. Tucker**, J. T. Cobb, and M. R. Azimi-Sadjadi, "Generalized likelihood ratio test for finite mixture model of K-distributed random variables" *Proc of IEEE DSP/SPE 2011 Workshop*, pp. 443-448, Jan. 2011. [PDF](Papers/DSPE11.pdf)

## 2010
T. G-Michael and **J. D. Tucker**, "Canonical correlation analysis for coherent change detection in synthetic aperture sonar imagery," *Proc of IEEE SAR/SAS 2010 Conference*, vol. 32, no. 4, pp. 117-122, Sep. 2010. [PDF](Papers/CCA_SAS-CCD.pdf)

N. Klausner, M. R. Azimi-Sadjadi, and **J. D. Tucker**, "Multi-sonar target detection using multi-channel coherence analysis," *Proc. of MTS/IEEE Oceans 2010 Conference*, pp. 1-7, Sept. 2010. [PDF](Papers/Oecans10.pdf)

**J. D. Tucker** and M. R. Azimi-Sadjadi,"Neyman pearson detection of K-distributed random variables," *Proc SPIE*, vol. 7664, pp. Q1-Q12, April 2010. [PDF](Papers/SPIE10.pdf)

## 2009
M. Kabatek, M. R. Azimi-Sadjadi, and **J. D. Tucker**, "An underwater target detection system for electro-optical imagery data,'' *Proc. of MTS/IEEE Oceans 2009 Conference*, pp. 1–8, October 2009. [PDF](Papers/Oceans09-EO.pdf)

N. Klausner, **J. D. Tucker**, and M. R. Azimi-Sadjadi, "Multi-platform target detection using multi-channel coherence analysis and robustness to the effects of disparity,'' *Proc. of MTS/IEEE Oceans 2009 Conference*, pp. 1–7, October 2009. [PDF](Papers/Oceans09.pdf)

N. Klausner, M. R. Azimi-Sadjadi, and **J. D. Tucker**, "Underwater target detection from multi-platform sonar imagery using multi-channel coherence analysis,'' *Proc. of IEEE SMC 2009 Conference*, pp. 2728–2733, 2009. [PDF](Papers/SMC09.pdf)

## 2008
**J. D. Tucker** and M. R. Azimi-Sadjadi, "Coherence-based underwater target detection and classification for side-scan sonar imagery," *Sea Technology Magazine*, vol. 12, pp. 10-14, December 2008. [PDF](Papers/seatechnology08.pdf)

**J. D. Tucker**, N. Klausner, M. R. Azimi-Sadjadi, "Target detection in m-disparate sonar platforms using multichannel Hypothesis Testing," *Proc. IEEE/MTS Oceans 2008*, pp. 1-7, September 2008. [PDF](Papers/oceans08.pdf)

**J. D. Tucker**, M. R. Azimi-Sadjadi, "Target detection from dual disparate sonar platforms using canonical correlations," *Proc. SPIE*, vol. 6553, pp. 65530U– 1–65520U–8, March 2008. [PDF](Papers/spie08.pdf)

## 2007
**J. D. Tucker**, M. R. Azimi-Sadjadi, and G. J. Dobeck, "Canonical coordinates for detection and classification of underwater objects from sonar imagery," *Proceedings of IEEE Oceans 2007*, pp. 1-6, June 2007. [PDF](Papers/oceans07.pdf)

**J. D. Tucker**, M. R. Azimi-Sadjadi, and G. J. Dobeck, "Coherent-based method for detection of underwater objects from sonar imagery," *Proc. SPIE*, vol. 6553, pp. 65530U– 1–65520U–8, April 2007. [PDF](Papers/spie07.pdf)

## Invited Talks
"Elastic Functional Changepoint Detection of Climate Impacts from Localized Sources" *Environmentrics TIES Webinar*, October 24, 2025, [Slides](https://jdtuck.github.io/presentations/TIES_Webinar_Oct_25/TIES_Webinar_Oct25.html) [Video](https://www.youtube.com/@environmetricswebinar3128)

"Bayesian Model Calibration: An Elastic Approach" *Colorado State University Statistics Seminar*, April 28, 2025, [Slides](https://jdtuck.github.io/presentations/CSU_April25/CSU_April25.html)

"Elastic Functional Data Analsyis: with Applications to Functional Changepoint" *Stony Brook SIAM Speaker*, November 19, 2024, [Slides](https://jdtuck.github.io/presentations/StoneyBrook_Nov_24/StoneyBrook_Nov_24.html)

"Bayesian Model Calibration: An Elastic Approach" *Purdue Statistical Colloquium*, February 23, 2024, [Slides](https://jdtuck.github.io/presentations/Purdue_Feb24/Purdue_Feb24.html) 

"Elasic Bayesian Model Calibration" *ASA SDNS Webinar*, December 04, 2023, [Slides](https://jdtuck.github.io/presentations/ASA_23_Calibration/index.html) [Video](https://www.youtube.com/watch?v=UNyOfL_zLX8&t=1469s)

"Elasic Bayesian Model Calibration" *FSU Shape Group Statistical Meeting*, January 24, 2023, [Slides](https://jdtuck.github.io/presentations/FSU_Jan23/FSU_Jan23.html) 

"Elastic Functional Data Analysis", *SMU Statistical Colloquium*, November 4, 2022, [Slides](Presentations/SMU_Nov_22.pdf)

"Elastic Functional Tolerance Bounds", *LANL Statistical Colloquium*, December 16, 2020

"Elastic Functional Data Analysis", *Brigham Young University Statistics Colloquium*, December 4, 2019 [Slides](https://jdtuck.github.io/presentations/FDA_Overview/FDA_Overview.html) 

"Sandia Applications of Functional Data Analysis", *University of Illinois Statistics Colloquium*, November 22, 2019

"Elastic Functional Data Analysis", *Australian National University Statistics Colloquium*, July 12, 2018

"Elastic Functional Data Analysis", *University of New Mexico Statistics Colloquium*, February 2, 2018

"Doppler Multi-INT Detection and Tracking", *NSWC-PCD Invited Lecture*, October 1, 2015 

"Alignment and Analysis of Proteomics Data using Square Root Slope Function Framework'', *CTW: Statistics of Time Warpings and Phase Variations 2012*, OSU MBI, Nov 7, 2012 [Slides](Presentations/MBI2012_Tucker.pdf)

"Statistical Analysis and Modeling of Elastic Functions'', *Department of Mathematical and Statistical Sciences, University of Alberta*, Aug 23, 2011. (Organizer: Yau Shu Wong) [Slides](Presentations/UA-Function_Warping.pdf)

## Patents
"Density-Based clustering of multidimensional Data" US Patent No. Applied

"Method and system for training an artificial neural network utilizing physics based knowledge" US Patent No. US12229934 [PDF](Papers/US12229934.pdf)

"Automated Change Detection Technique for Synthetic Aperture Sonar" US Patent No. US10049295B2 [PDF](Papers/US10049295.pdf)

